### ISSUE TITLE
Please clarify if this is a fork or the same project

### ISSUE THREAD

**Issue by NightTsarina** [9fans/drawterm#5]
Hi!

The original webpage at https://swtch.com/drawterm/ has not been touched in years, and has many broken links, including the link to the source code. I see this repository has more recent changes, but the Readme file still points to swtch.

Is this the new official source for drawterm, or just a private fork?

Thanks

**Comment by 0intro** [comment]
Hi,

Russ Cox maintained [drawterm](https://bitbucket.org/rsc/drawterm) as a Mercurial repository on Bitbucket until 2014. During the last couple of years, I was the only contributor.

In December 2014, Go moved from Mercurial to Git. Consequently, Russ Cox moved most of his projects from Mercurial to Git and from Bitbucket or GitHub. However, drawterm was left in place, probably due to lack of time and interest. Few months later, Google Code was shut down, so it wasn't possible to review contributions on Rietveld anymore.

In my side, I took Russ Cox's Mercurial repository from Bitbucket, converted it to Git, put it on GitHub and continued to contribute to it as I used to. I've also reviewed and merged changes from other contributors.

This drawterm repository is really a continuation of Russ Cox's repository. Russ Cox's repository on Bitbucket isn't maintained anymore and this one is still maintained and accepting contributions.

Recently, the people from 9front [forked](https://code.9front.org/hg/drawterm) drawterm to include their own changes (mainly support for the dp9ik protocol) and started from this repository as a reference.

While this repository isn't strictly the official repository, I would now consider it pretty much as the official repository.

**Comment by NightTsarina** [comment]
@0intro, Thanks for the explanation!

In this case, I will make the Debian package point to this repository, and upgrade to the latest commit. I presume you are not intending to cut releases?

**Comment by NightTsarina** [comment]
One thing you could do to make this less ambiguous is to change the readme to stop pointing to http://code.swtch.com/drawterm, as that is what made me think this was just a personal fork.

**Comment by 0intro** [comment]
I've removed all references to code.swtch.com from the README.
